const shell=document.getElementById('forgeApp');
const main=document.getElementById('home');
const sidebar=document.getElementById('sidebar');
const toast=document.getElementById('toast');
const homeMarkup=main.innerHTML;
let toastTimer;
function notify(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}
const routeNames={home:'Home',command:'Command Center',projects:'Projects',workspace:'Workspace',code:'Code / Assets',agents:'Agents',build:'Build',test:'Test',deploy:'Deploy / Runtime',runtime:'Runtime',infrastructure:'Infrastructure',security:'Security / Provenance',creative:'Creative',marketplace:'Marketplace',activity:'Activity',settings:'Settings'};
const nextRoute={projects:'requirements',workspace:'code',code:'build',agents:'build',build:'test',test:'deploy',deploy:'runtime',runtime:'infrastructure',infrastructure:'security',creative:'marketplace',marketplace:'activity',activity:'settings'};
function node(name,detail,kind='teal'){return `<div class="route-node ${kind}"><b>${name}</b><small>${detail}</small></div>`}
function flow(active){const steps=[['01','Intent','home'],['02','Projects','projects'],['03','Requirements','workspace'],['04','Work graph','code'],['05','Agents','agents'],['06','Build','build'],['07','Test','test'],['08','Deploy','deploy'],['09','Runtime','runtime']];return `<div class="workflow-strip">${steps.map(([n,label,key],i)=>`<a class="flow-step ${key===active?'current':''}" href="#${key}"><i>${n}</i><span>${label}</span>${i<steps.length-1?'<em>→</em>':''}</a>`).join('')}</div>`}
function routePage(key,kicker,title,summary,body){return `<div class="route-page"><header class="route-heading"><div><span class="eyebrow copper">FORGE / ${kicker}</span><h1>${title}</h1><p>${summary}</p></div><div class="route-actions"><button class="outline-btn" data-toast="View mode selected">◫ VIEW MODE</button><button class="copper-btn" data-route="command">⌘ COMMAND</button></div></header>${flow(key)}${body}</div>`}
function routeBody(key){
 if(key==='projects')return `<section class="route-grid two"><article class="panel route-hero"><div class="panel-head compact"><span class="eyebrow">PROJECT WORKSPACE</span><span class="eyebrow">READY</span></div><div class="route-empty"><span>▱</span><h2>No projects yet</h2><p>Projects give an intent a home. Connect a repository, define a boundary, and let the work graph grow from there.</p><div class="route-buttons"><button class="copper-btn" data-toast="Create project surface opened">+ CREATE PROJECT</button><button class="outline-btn" data-toast="Repository connection surface opened">CONNECT REPOSITORY</button></div></div></article><article class="panel route-graph-panel"><div class="panel-head compact"><span class="eyebrow">PROJECT LIFE CYCLE</span><span class="eyebrow">VISUAL WORKFLOW</span></div><div class="route-graph">${node('USER INTENT','starting point','copper')}${node('PROJECT','identity + boundary')}${node('REQUIREMENTS','what must be true')}${node('WORK GRAPH','dependencies + decisions')}${node('CODE / ASSETS','implementation')}${node('BUILD / TEST','evidence','amber')}${node('DEPLOY / RUNTIME','operating surface')}${node('OBSERVABILITY','feedback loop')}</div></article></section><section class="route-grid three"><article class="panel route-card"><span class="eyebrow">PROJECT STRUCTURE</span><h3>Organization</h3><p>Workspace, files, code, architecture, requirements, tasks, agents, and digital persons.</p><a href="#workspace">OPEN STRUCTURE →</a></article><article class="panel route-card"><span class="eyebrow">NEXT STEP</span><h3>Define requirements</h3><p>Turn an idea into a precise, traceable specification before work begins.</p><a href="#workspace">BEGIN REQUIREMENTS →</a></article><article class="panel route-card"><span class="eyebrow">CONTEXT</span><h3>Repository connection</h3><p>Bring source code into Forge without pretending it is connected before you approve it.</p><a href="#code">VIEW CODE SURFACE →</a></article></section>`;
 if(key==='workspace')return `<section class="route-grid two"><article class="panel route-hero"><div class="panel-head compact"><span class="eyebrow">REQUIREMENTS / WORK GRAPH</span><span class="eyebrow">EMPTY CONTEXT</span></div><div class="route-empty"><span>⌁</span><h2>Start with a clear brief</h2><p>Requirements are the bridge between intent and action. Capture outcomes, constraints, risks, references, and acceptance checks here.</p><button class="copper-btn" data-toast="Requirements editor opened">+ ADD REQUIREMENT</button></div></article><article class="panel route-graph-panel"><div class="panel-head compact"><span class="eyebrow">TRACEABILITY GRAPH</span><span class="eyebrow">NO NODES YET</span></div><div class="route-graph sparse">${node('INTENT','waiting','copper')}${node('REQUIREMENT','not defined','amber')}${node('ACCEPTANCE','not defined','amber')}${node('TASK','not defined')}${node('EVIDENCE','not defined')}</div></article></section><section class="panel checklist"><div class="panel-head compact"><span class="eyebrow">REQUIREMENTS WORKFLOW</span><span class="eyebrow">0 / 6 COMPLETE</span></div><div class="check-grid">${['State the outcome','Name the users and operators','Define boundaries and permissions','List dependencies and providers','Write acceptance checks','Approve the work graph'].map((x,i)=>`<button data-toast="Requirement step ${i+1} selected"><i>0${i+1}</i><span>${x}</span><em>OPEN →</em></button>`).join('')}</div></section>`;
 if(key==='code')return `<section class="route-grid two"><article class="panel route-hero"><div class="panel-head compact"><span class="eyebrow">CODE / ASSETS</span><span class="eyebrow">NO REPOSITORY CONNECTED</span></div><div class="route-empty"><span>⌑</span><h2>Nothing is connected yet</h2><p>Forge will show repositories, branches, files, generated assets, provenance, and review context here after you choose a source.</p><div class="route-buttons"><button class="copper-btn" data-toast="Connect repository surface opened">CONNECT REPOSITORY</button><button class="outline-btn" data-toast="Create workspace source surface opened">START WITHOUT REPOSITORY</button></div></div></article><article class="panel route-graph-panel"><div class="panel-head compact"><span class="eyebrow">CODE PROVENANCE</span><span class="eyebrow">WAITING FOR SOURCE</span></div><div class="route-graph">${node('PROJECT','context')}${node('BRANCH','not connected','amber')}${node('FILES','not indexed','amber')}${node('CHANGE','not proposed','copper')}${node('REVIEW','not opened','amber')}${node('ARTIFACT','not built')}</div></article></section><section class="panel route-table"><div class="panel-head compact"><span class="eyebrow">CODE SURFACE</span><span class="eyebrow">SOURCE · BRANCH · PROVENANCE · DIFF</span></div><div class="table-empty"><span>⌑</span><b>Connect a repository to see code here.</b><small>Forge will keep every change attributable to an intent, task, agent, and validation.</small></div></section>`;
 if(key==='agents')return `<section class="route-grid two"><article class="panel route-hero"><div class="panel-head compact"><span class="eyebrow">AGENT RUNTIME</span><span class="eyebrow">NO AGENTS ASSIGNED</span></div><div class="route-empty"><span>◈</span><h2>Give work a focused mind</h2><p>Agents will have roles, tools, permissions, memory, and a clear responsibility. Digital Persons will be a deeper layer later.</p><div class="route-buttons"><button class="copper-btn" data-toast="Agent builder surface opened">+ DEFINE AGENT</button><button class="outline-btn" data-toast="Agent templates opened">BROWSE TEMPLATES</button></div></div></article><article class="panel route-graph-panel"><div class="panel-head compact"><span class="eyebrow">AGENT WORK GRAPH</span><span class="eyebrow">NO ACTIVE WORK</span></div><div class="route-graph sparse">${node('INTENT','unassigned','copper')}${node('ROLE','not defined')}${node('TOOLS','not granted','amber')}${node('MEMORY','not created')}${node('EVALUATION','not started','amber')}</div></article></section><section class="route-grid three"><article class="panel route-card"><span class="eyebrow">ROLE</span><h3>One clear responsibility</h3><p>Define what the agent owns and what it must never do.</p></article><article class="panel route-card"><span class="eyebrow">CAPABILITY</span><h3>Tools with boundaries</h3><p>Grant only the providers and actions required for the work.</p></article><article class="panel route-card"><span class="eyebrow">IMPROVEMENT</span><h3>Evidence before change</h3><p>Capability improves through evaluation, feedback, and rollback.</p></article></section>`;
 if(key==='build'||key==='test'||key==='deploy'||key==='runtime'||key==='infrastructure'||key==='security')return `<section class="route-grid two"><article class="panel route-hero"><div class="panel-head compact"><span class="eyebrow">${routeNames[key].toUpperCase()}</span><span class="eyebrow">WAITING FOR WORK</span></div><div class="route-empty"><span>${key==='build'?'△':key==='test'?'✓':key==='deploy'?'↗':key==='runtime'?'◌':key==='infrastructure'?'▦':'◇'}</span><h2>${key==='build'?'No build target yet':key==='test'?'No evidence yet':key==='deploy'?'No release prepared':key==='runtime'?'No runtime connected':key==='infrastructure'?'No infrastructure connected':'No provenance chain yet'}</h2><p>${key==='build'?'A build begins when code, dependencies, and a target environment are known.':key==='test'?'Tests turn a proposed change into evidence Forge can trust.':key==='deploy'?'Deployment is a controlled handoff from validated artifact to an operating environment.':key==='runtime'?'Runtime shows what is alive, where it is, and how it is behaving.':key==='infrastructure'?'Infrastructure is where Forge keeps compute, storage, providers, secrets, and network boundaries.':'Every decision and artifact should be attributable, reviewable, and recoverable.'}</p><button class="copper-btn" data-toast="${routeNames[key]} setup surface opened">OPEN ${routeNames[key].toUpperCase()} SETUP</button></div></article><article class="panel route-graph-panel"><div class="panel-head compact"><span class="eyebrow">${routeNames[key].toUpperCase()} GRAPH</span><span class="eyebrow">EMPTY</span></div><div class="route-graph sparse">${node('SOURCE','not connected','copper')}${node('ARTIFACT','not produced')}${node('VALIDATION','not passed','amber')}${node('ENVIRONMENT','not configured','amber')}${node('OBSERVABILITY','not available')}</div></article></section><section class="panel checklist"><div class="panel-head compact"><span class="eyebrow">CONTROLLED WORKFLOW</span><span class="eyebrow">NEXT SURFACES</span></div><div class="check-grid">${[['SOURCE','code or intent'],['BUILD','repeatable artifact'],['TEST','evidence and checks'],['APPROVAL','risk-aware decision'],['RELEASE','versioned handoff'],['OBSERVE','health and rollback']].map(([a,b],i)=>`<a href="#${['code','build','test','settings','deploy','runtime'][i]}"><i>0${i+1}</i><span>${a}<small>${b}</small></span><em>OPEN →</em></a>`).join('')}</div></section>`;
 if(key==='creative'||key==='marketplace'||key==='activity'||key==='settings')return `<section class="route-grid two"><article class="panel route-hero"><div class="panel-head compact"><span class="eyebrow">${routeNames[key].toUpperCase()}</span><span class="eyebrow">READY FOR CONTEXT</span></div><div class="route-empty"><span>${key==='creative'?'✧':key==='marketplace'?'✦':key==='activity'?'◌':'⚙'}</span><h2>${key==='creative'?'Make room for creative work':key==='marketplace'?'A deliberate place for extensions':key==='activity'?'A record of what happened':'Shape how Forge behaves'}</h2><p>${key==='creative'?'Creative systems can hold 3D, world, video, animation, music, audio, painting, and other authored work without losing its technical context.':key==='marketplace'?'Modules, providers, asset packs, and agent templates belong here only when they are real and connected.':key==='activity'?'Forge will record decisions, agent work, validations, deployments, and system events with provenance.':'Settings should make permissions, providers, notifications, appearance, and operating boundaries legible.'}</p><button class="copper-btn" data-toast="${routeNames[key]} surface opened">OPEN ${routeNames[key].toUpperCase()} SURFACE</button></div></article><article class="panel route-graph-panel"><div class="panel-head compact"><span class="eyebrow">CONTEXT GRAPH</span><span class="eyebrow">EMPTY</span></div><div class="route-graph sparse">${node('FORGE','operating system','copper')}${node('WORKSPACE','context')}${node(routeNames[key].toUpperCase(),'not configured')}${node('PROVENANCE','waiting','amber')}${node('NEXT ACTION','not selected')}</div></article></section>`;
 if(key==='command')return `<section class="panel command-surface"><div class="command-focus"><span class="eyebrow copper">FORGE COMMAND / GLOBAL</span><h2>What are you trying to make?</h2><p>Forge will turn an intent into requirements, a work graph, focused agents, code, evidence, and an operating release.</p><div class="command-entry">Describe an intent, ask a question, or invoke a structured command…<b>→</b></div><div class="suggestion-row"><button data-route="projects">START A PROJECT</button><button data-route="workspace">DEFINE REQUIREMENTS</button><button data-route="agents">ASSIGN AN AGENT</button><button data-route="code">CONNECT CODE</button></div></div><aside class="command-context"><span class="eyebrow">CONTEXT</span><b>NO PROJECT SELECTED</b><small>No providers connected</small><small>No agents assigned</small><small>No runtime configured</small></aside></section>`;
 return `<section class="panel route-hero"><div class="route-empty"><span>⌂</span><h2>Home is the starting surface</h2><p>Choose a connected route from the navigation to continue.</p></div></section>`;
}
function go(key){key=routeNames[key]?key:'home';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',(x.getAttribute('href')||'')==='#'+key));if(key==='home'){main.innerHTML=homeMarkup}else{main.innerHTML=routePage(key,routeNames[key].toUpperCase(),routeNames[key],key==='command'?'A command surface that keeps your project context visible.':`A connected ${routeNames[key].toLowerCase()} surface for the Forge operating workflow.`,routeBody(key))}if(location.hash.slice(1)!==key)history.pushState(null,'','#'+key);if(innerWidth<780)sidebar.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('click',e=>{const feedback=e.target.closest('[data-toast]');if(feedback){notify(feedback.dataset.toast);return}const route=e.target.closest('[data-route]');if(route){e.preventDefault();go(route.dataset.route);return}const link=e.target.closest('a[href^="#"]');if(link){const key=link.getAttribute('href').slice(1);if(routeNames[key]){e.preventDefault();go(key)}}});
window.addEventListener('popstate',()=>go(location.hash.slice(1)||'home'));
document.getElementById('mobileMenu')?.addEventListener('click',()=>sidebar.classList.toggle('open'));
document.getElementById('collapseNav')?.addEventListener('click',()=>{shell.classList.toggle('collapsed');notify(shell.classList.contains('collapsed')?'Collapsed navigation state':'Expanded navigation state')});
document.getElementById('viewMode')?.addEventListener('click',()=>notify('Atlas view selected'));
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();notify('Command surface focused');go('command')}if(e.key==='Escape')sidebar.classList.remove('open')});
const voiceButton=document.getElementById('voiceButton');
if(voiceButton)voiceButton.addEventListener('click',()=>{voiceButton.classList.toggle('recording');notify(voiceButton.classList.contains('recording')?'Voice input ready · visual recording state':'Voice input paused · visual state')});
if(location.hash&&routeNames[location.hash.slice(1)])go(location.hash.slice(1));
